FROM php:7.1-apache

RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
	libpng-dev \
    libicu-dev \
    libxml2-dev \
    libpq-dev \
    nano vim \
    wget \
    zip unzip \
    git 

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
	
RUN docker-php-ext-install -j$(nproc) iconv intl xml soap mcrypt zip opcache pdo pdo_pgsql pdo_mysql mysqli gd mbstring bcmath

RUN a2enmod rewrite